# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# title: Your awesome title
# email: your-email@example.com
description: >-
  Ampleforth Improvement Proposals (AIPs) describe standards for the Ampleforth
  platform, including core protocol specifications, client APIs, and supporting
  applications.
url: "https://aips.ampleforth.org"
repository: ampleforth/AIPs
twitter_username: "AmpleforthOrg"
github_username:  Ampleforth
header_pages:
  - all-aip.html
  - all-accp.html
twitter:
  card: summary
  username: "AmpleforthOrg"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag
#  - jekyll-feed

permalink: /:slug

defaults:
  - scope:
      path: "AIPs"
    values:
      layout: "aip"
  - scope:
      path: "ACCP"
    values:
      layout: "accp"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - accp-x.md
  - aip-X.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
